### ISSUE TITLE
Option to hide dynisland without killing daemon

### ISSUE THREAD

**Issue by fabolous005** [cr3eperall/dynisland#7]
Hey,
it would be cool to allow toggling the visibility of dynisland either either via an command or by specific Signals that may be sent to dynisland.
My current solution is to always kill the daemon and that's... meh
What do you think? Can this be easily implemented?

**Comment by cr3eperall** [comment]
I've just added the option to add/remove css classes from the `DynamicLayout` layout manager with 8f25e67fbf7698200c6f1e7c49c1dabfb2d43429.

So now you could put this in dynisland.scss:
```scss
.activity-container{
  transition-property: transform, opacity;
  transition-duration: 1s;
  &.hide-window{
  transform: translate(0px, -50px);
  opacity: 0%
  }
}
```
To hide the window you do `dynisland layout add-css hide-window` and to show it again you do `dynisland layout remove-css hide-window`.

Does this solve the issue?
